image: alpine:latest

pipelines:
  branches:
    main:
      - step:
          name: doc_to_readme
          .push: &push |
            lines=$(git status -s | wc -l)
            if [ $lines -gt 0 ];then
              git add "README.md"
              git commit -m "Auto-update README.md [skip ci]"
              echo "git push 'https://x-token-auth:${GIT_PUSH_TOKEN}@bitbucket.org/${BITBUCKET_REPO_FULL_NAME}' main"
              git push "https://x-token-auth:${GIT_PUSH_TOKEN}@bitbucket.org/${BITBUCKET_REPO_FULL_NAME}" main
            fi 
          script:
            - apk add bash git
            - apk add --no-cache python3
            - git fetch
            - git clone 'https://github.com/ziselsberger/doc_to_readme.git'
            - cp ./doc_to_readme/src/doc_to_md.py .
            - rm -rf doc_to_readme
            - python3 doc_to_md.py -f README.md
            - rm doc_to_md.py
            - *push
