name: Update README.md (use action)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  doc-to-readme:
    uses: ziselsberger/doc_to_readme@v1
    with:
      PATH_TO_README: "README.md"
      EXCLUDED_MODULES: "doc_to_md"
