name: Update README.md

on:
  push:
    branches:
      - main

jobs:
  update-docu:
    runs-on: ubuntu-latest
    steps:
      - name: Use external action
        uses: ziselsberger/doc_to_readme/.github/workfows/use_doc_to_readme.yml@main
