name: Update README.md (use action)

on:
  workflow_dispatch:
    
jobs:
  doc-to-readme:
    runs-on: ubuntu-latest
    uses: ziselsberger/doc_to_readme@main
    with:
      PATH_TO_README: "README.md"
      EXCLUDED_MODULES: "doc_to_md"
